### PR TITLE
Added 4 New bit Routines.

### PR DESCRIPTION
**Pull request by QB64Cobalt**
Added _READBIT, _SETBIT, _RESETBIT, and _TOGGLEBIT

### CODE REVIEW

**Comment by FellippeHeitor** [comment]
Best to make it to dev branch

**Comment by AshishKingdom** [comment]
What is the use of these all?

**Comment by FellippeHeitor** [comment]
Reading, setting, resetting and toggling bits.

**Comment by AshishKingdom** [comment]
I will happy to see practical application for these functions. :) 
Thanks for your reply.

**Pull request closed without merging**
